include test_smoke
include test_derep_fastq
include test_dada
include test_learn_errors
include test_merge_pairs
include test_fastq_filter
include test_filter_and_trim
include test_remove_bimera_denovo
